import "@/styles/globals.css"
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";
import React from "react";


export const metadata = {
  title: "Nike.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header />
        <main className="w-full md:px-10">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
